<?php

/**
 * @file
 * Primary module hooks for VP Analytics module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function vp_analytics_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'vp_analytics') {
    /** @var \Drupal\Core\Queue\QueueInterface $queue */
    $queue = \Drupal::queue('vp_analytics_games');
    $queue->createItem($entity->id());
  }
}


function vp_analytics_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
  $values = [
    'label' => 'Test VP Analytics 1',
    'field_pilot_code' => 'GRC',
    'field_virtual_patient' => '166f2395-61ad-403e-9180-a8131c39f184',
    'field_profile_id' => 1,
    'field_playtime' => 3600,
    'field_score' => 80,
    'field_success' => TRUE,
  ];
  // $entity = \Drupal\vp_analytics\Entity\VpAnalytics::create($values);
  // $entity->save();
  // $result = \Drupal::service('vp_analytics.post')->postData($entity);
}
