rest.resource.configuration.vp_analytics:
  type: mapping
  mapping:
    methods:
      type: sequence
      label: 'Allowed HTTP methods'
      sequence:
        type: string
    formats:
      type: sequence
      label: 'Allowed formats'
      sequence:
        type: string
    authentication:
      type: sequence
      label: 'Authentication providers'
      sequence:
        type: string