<?php

/**
 * @file
 * Primary module hooks for VP Visual Editor module.
 */

/**
 * Implements hook_entity_base_field_info().
 * function vp_visual_editor_entity_base_field_info(EntityTypeInterface $entity_type) {
 * $fields = [];
 * if ($entity_type->id() === 'virtual_patient') {
 * $fields['field_visual_metadata'] = BaseFieldDefinition::create('text_long')
 * ->setLabel(t('VP visual metadata'))
 * ->setDescription(t('Stores some visual metadata for nodes.'))
 * ->setRevisionable(FALSE)
 * ->setTranslatable(FALSE);
 * return $fields;
 * }
 * }
 */
