<?php

/**
 * @file
 * Primary module hooks for audit module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function audit_theme(): array {
  return [
    'audit_question' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for audit question templates.
 *
 * Default template: audit-question.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the audit question information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_audit_question(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function audit_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish audit questions.
      $storage = \Drupal::entityTypeManager()->getStorage('audit_question');
      $audit_question_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($audit_question_ids) as $audit_question) {
        $audit_question->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize audit questions.
      $storage = \Drupal::entityTypeManager()->getStorage('audit_question');
      $audit_question_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($audit_question_ids) as $audit_question) {
        $audit_question->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function audit_user_predelete(UserInterface $account): void {
  // Delete audit questions that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('audit_question');
  $audit_question_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($audit_question_ids)
  );
}

function audit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id): void {
  // @todo
}
